name: Lint GitHub Actions workflows

on:
  pull_request:
    paths:
      - ".github/**"
  push:
    branches:
      - "main"
    paths:
      - ".github/**"

jobs:
  actionlint:
    runs-on: namespace-profile-2x4-ubuntu-2404
    if: github.repository_owner == 'zed-industries'
    permissions:
      contents: read
    env:
      VERSION: 1.7.7
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Check workflow files
        run: go run github.com/rhysd/actionlint/cmd/actionlint@v${{ env.VERSION }} -color
        shell: bash
